name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1','8.2','8.3']
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Install OpenBLAS 
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libopenblas-dev liblapacke-dev
          pkg-config openblas --libs

      - name: LS HOME
        run: |
          ls -la $HOME
          ls -la $HOME/.local
          ls -la /usr/lib/x86_64-linux-gnu/libopenblas.so.0
          ls -la /etc/alternatives/libopenblas.so.0-x86_64-linux-gnu
          ls -la /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so.0
          ls -la /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: ffi

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit.xml
          version: 10.5
          php_version: ${{ matrix.php }}
          php_extensions: ffi

