name: tests

on: 
  push:
      branches:
          - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: macOS
            os: macos-latest
            php: '8.3'

##            - name: PHP8.1
##            os: ubuntu-latest
##            php: '8.1'
##          - name: PHP8.2
##            os: ubuntu-latest
##            php: '8.2'
##          - name: PHP8.3
##            os: ubuntu-latest
##            php: '8.3'
##          - name: Windows
##            os: windows-latest
##            php: '8.3'
    
    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpunit:10.5, phpstan
          #ini-values: "memory_limit=512M"
          extensions: ffi

      - name: Install OpenBLAS
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt install -y libopenblas0-openmp liblapacke

      - name: Checkout codes
        uses: "actions/checkout@v4"

      #- name: Composer
      #  uses: php-actions/composer@v6
      #  with:
      #    php_version: ${{ matrix.php }}
      #    php_extensions: ffi

      - name: Composer
        run: composer update

      #- name: PHP Static Analysys
      #  uses: php-actions/phpstan@v3
      #  with:
      #    php_version: ${{ matrix.php }}
      #    path: src/

      - name: PHP Static Analysys
        run: phpstan

      #- name: PHPUnit Tests
      #  uses: php-actions/phpunit@v3
      #  with:
      #    configuration: tests/phpunit.xml
      #    version: 10.5
      #    php_version: ${{ matrix.php }}
      #    filter: ReleaseTest

      - name: PHPUnit Tests
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: phpunit -c tests

      - name: PHPUnit Tests
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          brew install openblas
          phpunit -c tests --filter ReleaseTest

